### PR TITLE
Added some OIDs for S/MIME.

### PR DESCRIPTION
**Pull request by duesee**
I don't know if you are interested in this kind of PR, but since it is useful for me, it may be for others.

### CODE REVIEW

**Comment by duesee** [comment]
Since I need a Google account to sign the CLA, I would prefer to close this PR. Sorry for the inconvinience.

**Comment by davidben** [comment]
What specification are the OIDs you want from? I'm afraid I can't merge the PR without a CLA, but I'm happy to go transcribe them from original specification myself if that would be useful for you.

**Comment by duesee** [comment]
Oh, this is very kind of you! :-) Just in case: I'm fine with signing the CLA, but don't wanted to go through creation of a new account, etc. If there is a simple way to agree on the CLA I would be happy to do that!

The OIDs I provided were those you typically find in an S/MIME message (RFC5751 and RFC5652). To be honest... I crafted these very unsystematically. I am not sure if there is even a defined set of OIDs used in S/MIME.

**Comment by davidben** [comment]
(Sorry about the delay. I forgot about this.)

I'm not sure if there is a way to do it without an account? But I wouldn't know since it's surely changed a lot since I last went through this.

Anyway, I went and transcribed a bunch of OIDs from those two specifications and a few related ones (I figured I may as well fill out the corresponding OID arcs) in 3fa2e9dc49fcf190f54efe74c0e33a519d385638. Does that cover what you need?

**Comment by duesee** [comment]
Yes, this will probably cover most OIDs in S/MIME. If I find more usual ones, I will collect them and try the CLA-thing :-)

**Pull request closed without merging**
